### ISSUE TITLE
Cannot build the sample project on iPhone 

### ISSUE THREAD

**Issue by dirablue** [CANDY-HOUSE/SesameSDK_iOS_with_DemoApp#22]
Hi @Jerming 

It seems I cannot build this sample project on iPhone 6
How can I fix this error ?

Device: iPhone 6
OS: 12.4.8

```
Command PhaseScriptExecution failed with a nonzero exit code
```

<img width="1029" alt="2020-08-27_11-58-55" src="https://user-images.githubusercontent.com/708452/91379050-bfc1b600-e85c-11ea-81c0-b5886696875f.png">

**Comment by Jerming** [comment]
hey @dirablue thanks for opening the issue.
Could you try on the new release fd8be34 ?Thank you.

**Comment by dirablue** [comment]
@Jerming Hi Jerming. Thank you for your update!
Let me try it later.
