### ISSUE TITLE
Sesame3 WebAPIの施開錠にて、ステータス200が返るが、sesame3が動かない件について

### ISSUE THREAD

**Issue by econron** [CANDY-HOUSE/SesameSDK_iOS_with_DemoApp#36]
メールでカスタマーサポートの方と何度かやりとりさせていただいた結果、
issueにて質問する、というお話になり投稿します。

タイトルの通りの事象が起き、原因が自分で特定できませんでした。
もし思い当たる原因や不足している行為などがありましたら、ご指摘いただきたく思います。
前提は下記のとおりです。

①sesame3をwi-fiモジュールとペアリング。iOSの公式アプリから施開錠できることを確認。
②ステータス取得APIを下記のように利用、実行した結果は以下の通り

実装：

```
url = f'https://app.candyhouse.co/api/sesame2/{uuid}'
headers = {'x-api-key' : api_key}
res = requests.get(url, headers=headers)
print(res.status_code, res.content)
```
結果：
```
200 b'{"batteryPercentage":100,"batteryVoltage":6.12316715542522,"position":-3,"CHSesame2Status":"locked","timestamp":1628124666,"wm2State":true}'
```

③同じUUIDとAPIKEYを利用して、施開錠APIを下記のように利用

実装：
secret_keyはカスタマーサポートの方とのやり取り（後述）でいただいた内容で実装しました。

```
# 公式ドキュメントと違う箇所
secret_key = secret_key[2:34]

# 以降はほぼ公式ドキュメントと等しいと思います。　https://doc.candyhouse.co/ja/SesameAPI
cmd = 83  # 88/82/83 = toggle/lock/unlock
history = 'test5'
base64_history = base64.b64encode(bytes(history, 'utf-8')).decode()

headers = {'x-api-key': api_key}
cmac = CMAC.new(bytes.fromhex(secret_key), ciphermod=AES)

ts = int(datetime.datetime.now().timestamp())
message = ts.to_bytes(4, byteorder='little')
message = message.hex()[2:8]
cmac = CMAC.new(bytes.fromhex(secret_key), ciphermod=AES)

cmac.update(bytes.fromhex(message))
sign = cmac.hexdigest()
# 鍵の操作
url = f'https://app.candyhouse.co/api/sesame2/{uuid}/cmd'
body = {
    'cmd': cmd,
    'history': base64_history,
    'sign': sign
}
res = requests.post(url, json.dumps(body), headers=headers)
print(res.status_code, res.text)
```

結果：
`200`

ただしsesame3は反応せず。

secret_keyを取得する手順：

```
こちらUUID、API KEY、secret keyの入力間違いの可能性が高いとのことでございます。

お手数をお掛け致しますが、再度入力に間違いがないかご確認頂けますでしょうか。
また、一度以下の手順に沿ってsecret keyを取得し、再度お試し頂きますようお願い致します。

①事前にお使いのセサミのQRコードのスクリーンショットをご用意頂く

②以下のリンクを開く
https://zxing.org/w/decode.jspx

③「ファイルを選択」をクリックし、QRコードのスクリーンショットを送信

④一番下の「Parsed Result」に表示されている文字を全てコピーする

⑤以下のリンクを開く
https://semalt.tools/en/url-parser

⑥コピーした文字をURL欄にペーストする

⑦sk = の欄にある文字を全てコピーする

⑧以下のリンクを開く
https://base64.guru/converter/decode/hex

⑨コピーした文字をBase64*の欄に入れ、Convert Base64 to Hexをクリック

⑩Hexの欄で表示された文字の３文字目から３４文字目がsecret key（３２文字）になります。
```

以上、丁寧にご対応いただいたものの動かせませんでした。
どうぞよろしくお願いいたします。

**Comment by econron** [comment]
自己解決しました。

**Comment by aky2006** [comment]
econron さん、自己解決されたとのことですが、どのように解決されたかご教授いただけませんでしょうか。
同じような事象をAndroidの方に起票しております。

**Comment by youyanntoto** [comment]
@econron 
私も同じ状況で困っています。
原因が何だったかだけでもご教授いただけないでしょうか？
https://github.com/CANDY-HOUSE/SesameSDK_Android_with_DemoApp/issues/22

**Comment by econron** [comment]
@youyanntoto 
すいません。すっかり忘れてました。お返事します。
自分ハードウェア周りは強烈に弱いので正確なワードでなかったらすいません。

とりあえず、下記の条件で解決してます。

デバイス：
・sesameのwi-fiモジュール
https://jp.candyhouse.co/products/new-wifi
・sesame3
・wi-fiルーター（uqwimaxとか）

やり方：
・sesame3 webAPIの公式にあるようなソースの書き方を真似して、pythonソースを用意しておく
or
https://zenn.dev/key3/articles/6c1c2841d7a8a2
こちらの記事に従い用意しておく

動かすには
・api key
・QRコード内の文字列
・sesame3のUUID
が必要です。
zennの上記記事を読んでみてください。

①スマホのwi-fi接続先を、wi-fiルーターにする
②sesame3とsesameのwi-fiモジュールを、スマホの専用アプリに登録する
③スマホアプリ上で登録したsesameのwi-fiモジュールをタップし、登録したsesame3を紐付ける
④実際にpythonスクリプトで叩いてみる
→ 動けば成功

という感じです。

--------------
自分ができなかったのは、wi-fiモジュールとsesame3をペアリングしてなかったことが原因でした。

もし不明点があればまた頂戴できれば速くレス返します。

**Comment by youyanntoto** [comment]
@econron 
情報ありがとうございます！
wi-fiモジュールとのペアリングとQRコード内の文字列を再確認したところ解決しました。

https://sesame-qr-reader.vercel.app/

**Comment by econron** [comment]
@youyanntoto 
自分もQRコードのSKの箇所の切り出しをミスしたり、ペアリングしなかったり・・などで詰まりました。
お役に立てて良かったです。
