### ISSUE TITLE
Does the DemoApp work with Sesame 4?

### ISSUE THREAD

**Issue by huy-nm** [CANDY-HOUSE/SesameSDK_iOS_with_DemoApp#39]
- I use the SDK to connect with the Sesame 4 but the app is crash
- When parse the QR Code, it detect type is 4, but the enum in the demo doesn't have the enum for sesame 4

**Comment by Jerming** [comment]
Yes!
And by the way, the SDK will be updated soon by September. 
The SDK 3.0 will support new hardware such as Sesame5, and will be open source.
Please stay tuned. Thank you!
