### ISSUE TITLE
Can't install Sesame SDK with CocoaPods

### ISSUE THREAD

**Issue by takao-akiyoshi** [CANDY-HOUSE/SesameSDK_iOS_with_DemoApp#44]
We can't install Sesame SDK with CocoaPods cuz `CANDY-HOUSE/SesameSDK_iOS.git` is deleted.
Thus, we can't build our App by CI/CD.

Of course, adding the framework manually would not be a problem, but it is inconvenient, so please restore the repository ASAP!

**Comment by Jerming** [comment]
https://github.com/CANDY-HOUSE/SesameSDK_iOS_with_DemoApp/tree/8cd9b6060393290b8270110404751ee6b5cf55f2/SesameSDK_iOS

こちらのご使用お願い申し上げます。

**Comment by KAZUMA87** [comment]
@Jerming 
URLとして提示された方では、CocoaPodsからでは利用できないので、CocoaPodsから利用する方法を教えてほしい。
展開したフォルダーからSesameSDK_iOSをXcodeにドラッグ&ドロップしました。
Posdsフォルダーもドラッグ&ドロップすればOKでしょうか？

**Comment by Jerming** [comment]
@KAZUMA87 
ご質問頂きありがとうございます。
CocoaPodsからの利用については暫く対応の予定がございませんが、Swift Package Managerへの対応を進めております。こちらにてhttps://github.com/CANDY-HOUSE/SesameSDK_iOS_with_DemoApp/tree/chore/spm
作業を行っており、現在はテスト段階です。12月中にはmasterブランチにマージする予定です。

また、Podsフォルダーについてのご質問ですが、CocoaPodsを使わずにライブラリを導入する場合、通常は必要なファイルやフレームワークをXcodeプロジェクトにドラッグ&ドロップで追加するだけで大丈夫です。Podsフォルダーをドラッグ&ドロップする必要はありません。もし追加方法について不明な点があれば、お気軽にご質問ください。

**Comment by takao-akiyoshi** [comment]
上記のご対応の影響でSPMでしか利用できなくなってしまっています。
外部ライブラリの管理ツールが複数になるのか管理コストが高まるので至急CocoaPodsにも対応した形に戻してください
