### ISSUE TITLE
Can't register Sesame 3 and 4 with new SDK (version 3.0)

### ISSUE THREAD

**Issue by LiveSmartDev** [CANDY-HOUSE/SesameSDK_iOS_with_DemoApp#45]
We can't register Sesame 3 and 4 with new SDK.
I guess new SDK is wip now cuz it seems that it does nothing in API class.

When will it be officially released?
 
- https://github.com/CANDY-HOUSE/SesameSDK_iOS_with_DemoApp/blob/master/SesameSDK/Shared/Ble/SesameOS2/Sesame2/CHSesame2Device%2BRegister.swift#L27
- https://github.com/CANDY-HOUSE/SesameSDK_iOS_with_DemoApp/blob/master/SesameSDK/Shared/Server/CHAccountManager%2BAPIRequest.swift#L12

**Comment by Jerming** [comment]
Please  allow a few days. We are working on the issue right now.

**Comment by Jerming** [comment]
対応させて頂きました。ご確認頂けますと幸いです。
We have address the issue. Please check it out. Thanks!

master f1d41de
@LiveSmartDev
