### ISSUE TITLE
CHConfiguration.shared.apiKey and CHConfiguration.shared.clientId no longer exist

### ISSUE THREAD

**Issue by midway** [CANDY-HOUSE/SesameSDK_iOS_with_DemoApp#54]
The demo application has the apiKey field and the clientId field setting lines of code commented out.  Due to the lack of documentation for the iOS version I can not find where these fields have been moved to and what the appropriate way to initialize them is now.  Have they been removed entirely?

**Comment by Jerming** [comment]
Yes, Mike, the apiKey field and the clientId field are no longer necessary. We've streamlined the project to minimize third-party dependencies, making it cleaner and simpler.
