### ISSUE TITLE
It seems BLE connection is more unstable than older SDK.

### ISSUE THREAD

**Issue by takao-akiyoshi** [CANDY-HOUSE/SesameSDK_iOS_with_DemoApp#59]
It takes a long time for the status to `locked/moved/unlocked/iotConnected/iotDisconnected`, even though it is placed in close proximity. (Especially SESAME Touch)
And, It takes more long time to discover  unregistered devices  then older SDK.

**Comment by Jerming** [comment]
大切なご意見ありがとうございます！
Sesame3とSesame4のBluetoothアドバタイジングは0.5秒ごとに行われ、Sesame TouchのBluetoothアドバタイジングは1秒ごとに行われますので、反応が遅く感じられるかもしれません。Sesame TouchのBluetoothアドバタイジングの頻度を高めることも可能ですが、それによってSesame Touchの消費電力が増加します。WiFiモジュールは常にSesame TouchとBluetooth接続を維持しており、常に接続されている場合、Bluetoothアドバタイジングの頻度を下げてもユーザー体験に影響はないと思いました。これは総合的な検討の結果でした。
