### ISSUE TITLE
In Xcode and got the error AWSCognitoIdentityErrorDomain.

### ISSUE THREAD

**Issue by KAZUMA87** [CANDY-HOUSE/SesameSDK_iOS_with_DemoApp#62]
SesameSDKを用いて、SesameとWifiモジュールを繋げるコードを書いています。
Xcodeで開発をしているが、実行したところ、
failure(Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=10 "(null)" UserInfo={__type=ResourceNotFoundException, message=Identity 'ap-northeast-1:（16進数）' not found.})
というエラーが表示されました。

これが原因かどうかわかりませんが、SesameとWifiモジュールは接続されているが、Wifiモジュールがネットに繋がっていない状態になっていいます。これはどこかおかしいのか、実装方法に問題があるのか教えてもらえると助かります。

**Comment by Jerming** [comment]
@KAZUMA87 さま
ご報告いただいたエラー：
failure(Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=10 "(null)" UserInfo={__type=ResourceNotFoundException, message=Identity 'ap-northeast-1:(16進数)' not found.})
は、スマートフォンのアプリがCANDY HOUSEのアカウントにログインしていないことを示していますが、これは「SesameとWifiモジュールを接続すること」と「Wifiモジュールをネットに接続すること」には影響しません。

「Wifiモジュールがネットに接続されていない状態」に関しては、まずSesameのアプリを使用して接続が正常に行えるかどうかを試していただき、他に原因がないかご確認いただければと思います。ありがとうございます。
