### ISSUE TITLE
Which license actually applied?

### ISSUE THREAD

**Issue by soltia48** [CANDY-HOUSE/SesameSDK_iOS_with_DemoApp#73]
# Summary

According to the LICENSE, this repository is applied the MIT license. However, the "SesameSDK Terms of Use" linked from README.md includes proprietary terms that are inconsistent with the MIT License.

# Request

Please clarify which license applies to the latest code in this repository. Otherwise, no one can use it without legal risk.

<img src="https://media1.tenor.com/m/t7_iTN0iYekAAAAd/sad-sad-cat.gif" width="256" height="256" />

**Comment by tkgstrator** [comment]
@soltia48 I completely agree with you.

**Comment by Jerming** [comment]
MIT LICENSE. 
Sorry for being confusing.
@soltia48 @tkgstrator

**Comment by tkgstrator** [comment]
@Jerming Thank you for your quick response.

![cat-cat-jumping](https://github.com/CANDY-HOUSE/SesameSDK_iOS_with_DemoApp/assets/29420801/03e7d767-7b9b-4cd0-a03b-daa45139ae1f)
